version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: nyc_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: nyc_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: nyc_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nyc_jupyter
    volumes:
      - ./app:/app
      - ./data:/app/data
    ports:
      - "8888:8888"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata:
